### ISSUE TITLE
chrome on linux with one client fails

### ISSUE THREAD

**Issue by WIP42** [krukow/stomple#1]
Hi Karl, thanks for the great intro on websocket based STOMP!, hope this issue can be answered and im missing something simple/stupid...:-)

I've experianced this in other websockets (and flash) clients (some pubsub ones) so dunno if its a general javascipt problem but also got same problem under Titanium environment. 

If only one client is open, the connect fails:
sub fail    transactional-chat.html:88

Opening the second client gets the same error, BUT once you refresh the second client, the 1st gets connection attempt through! - SUBSCRIBE, RECEIPT and sub ok..

Similarly to get the second one to connect, you have to open a third window and refresh that page to get the second one to gto through SUBSCRIBE, RECEIPT and sub ok..

What am I missing?

**Comment by WIP42** [comment]
same issue using nodered with websockets: http://github.com/fictorial/nodered/issues/#issue/7

**Comment by WIP42** [comment]
output looks like:
<code>
>>>>
CONNECT
login:guest
passcode:guest

sub fail
--------------------------------
# 2nd browser window loaded, then refreshed, allowing 1st to connect?
--------------------------------
...stomple.js:1028

<<<<
CONNECTED
session:31029482
--------------------------------
>>>>
SUBSCRIBE
destination:jms.topic.chat
receipt:31029482-m-1
--------------------------------
<<<<
RECEIPT
receipt-id:31029482-m-1
--------------------------------
sub ok..
</code>

**Comment by krukow** [comment]
I've not experienced this myself, but I've only tried on MacOSX and Windows.

There is more information available when it fails. Try replacing the call to subscribe with:
    client.subscribe({
        handler: msgHandler.fn,
        scope: msgHandler,  
        success: function() {//did subscription succeed?  
            console.log("sub ok..");  
        },
        failure: function(reason) {//did subscription fail?
            console.log(reason);
        } 
    });

**Comment by WIP42** [comment]
great, thank you very much Karl, ill try it out!
Yup, I'm on Ubuntu 10.04, using chrome stable currently @ 5.0.375.86
Fails seemingly with a timeout. is websocket supposed to be undefined?:
<code>
Object
frame: Object
reason: "timeout"
websocket: undefined
**proto**: Object
</code>
...loading each of the 2 windows initially have a timeout as above. after reloading the 2nd, the 1st window client connects but 2nd still shows timeout. ill give Win XP a try too...

**Comment by krukow** [comment]
No: websocket undefined is a minor bug. I'll fix that.

It looks like you problem is server side, not client side. If it is your linux, configuration or HornetQ, I don't know. Looks like the initial connection takes a long time to establish, or hangs somehow. You could as the HornetQ guys.

If you want to can increase the timeout.

**Comment by krukow** [comment]
I've looked through the code, and it makes no sense to me how websocket can be undefined in the log. I've made some minor changes, could you try with the updated script?

If it fails: then please try
 in the console/inspector: just write new WebSocket('ws://localhost:61614/stomp') and see what that returns?

**Comment by WIP42** [comment]
Thanks again, FYI its working in virtualbox on windows XP 1st time page loads in Chrome. Working with plain vanilla hornetq 2.1.1 FINAL running on jre 6u21, a copy of same setup ito software on linux client.

I doubt its a timout because reloading the _other_ tab/window makes the window connect instantly... no time delays.

Il ldefinitely try the suggested updates. Whats interesting is seeing it in the Webkit-based Titanium Developer environment too - makes me think the linux version of Webkit may be at fault.

Will see and report back!p

**Comment by WIP42** [comment]
Hi Karl, many thanks for the help.

Tested with the updated client code, no timeout changes, the Websocket is now not reported as null any more but still timeout even after reloading page:
<code>
>>>>
CONNECT
login:guest
passcode:guest
---------------------
Object
frame: Object
reason: "timeout"
websocket: WebSocket
**proto**: Object
</code>

Testing with second client opening it makes no difference, still no connections/response from entering the message. when refreshing the second client though, the 1st is connected while the second times out eventually like:

<code>
>>>>
CONNECT
login:guest
passcode:guest
---------------------
Uncaught TypeError: Cannot call method 'send' of null   ...stomple.js:946
</code>

And vice versa, refresh 1st client-1nd connects and 1st times out like above

Typing "new WebSocket('ws://localhost:61614/stomp')" in the debug console
seems to pass ok:
<code>
WebSocket
URL: "ws://localhost:61614/stomp"
bufferedAmount: 0
onclose: null
onerror: null
onmessage: null
onopen: null
readyState: 0
**proto**: Object
</code>

**Comment by WIP42** [comment]
...ok I know it sounds like I'm going in circles, but the client is not consistently failing now in this way for me, latest symptoms after tests above, I reload the 2nd client then the 1st and second conects successfully (only after reloading the 2nd window's page), 

Now when I type into the 1st window, I can see the results only in the 2nd window

And when i type into the second window, I can see its own message appear in its lit but none on the 1st window...

The changes made to the client code seems to have some effect, makes describing what happens for me/how it fails less consistent-if that even makes sense;-)

**Comment by krukow** [comment]
Sounds very strange - and I am not sure what I can do about it.

Try the following which logs even more, and let me know

```
        var client = Stomple.create_client({
          url: "ws://localhost:61614/stomp",
          destination: "jms.topic.chat",
          login: "guest",
          passcode: "guest",
            socketOpen: function() {
                console.log("socket opened");
            },

            socketMessage: function(msg) {
                console.log("socket msg");
                console.log(msg);
            },

            socketClose: function(e) {
                console.log("socket close");
                console.log(e);
            },

            socketError: function() {
                console.log("socket error");
                console.log(client.websocket);
                return false;
            }

      });
      var msgHandler = {
            fn: function(msg) {
                var c = document.getElementById('content');
                c.innerHTML = c.innerHTML + '<br>' + msg.body;
            }
      };
      client.subscribe({
        handler: msgHandler.fn,
        thisObj: msgHandler,

        success: function() {//did subscription succeed?
            console.log("sub ok..");
        },
        failure: function(reason) {//did subscription fail?
            console.log(reason);
        }
      });
```

**Comment by krukow** [comment]
Also, just to rule out that this actually is an error in the stomple.js could you try Jeff Mesnills stomp-websocket?

/Karl

**Comment by WIP42** [comment]
Hi Karl, thanks for adding the logging and the code above, still getting to know websockets, nice to see how to add the socket handler methods.

<code>

>>>>
CONNECT
login:guest
passcode:guest

---------------------

Object
frame: Object
reason: "timeout"
websocket: WebSocket
**proto**: Object

---------------------

socket close

---------------------

Event
bubbles: false
cancelBubble: false
cancelable: false
clipboardData: undefined
currentTarget: WebSocket
defaultPrevented: false
eventPhase: 2
returnValue: true
srcElement: WebSocket
target: WebSocket
timeStamp: Mon Aug 09 2010 14:15:07 GMT+0200 (SAST)
type: "close"
**proto**: Object
</code>

Ill try the stomp-websocket code next, didnt have much time the last week so apoplogies for being quiet.

Pierre

**Comment by WIP42** [comment]
With the stomp-websocket chat example client I get only "Opening Web Socket..." from settings:
<code>
Server URL   ws://localhost:61614/stomp
Login   guest
Password   guest
Destination   /queue/test
</code>
After pressing Connect, no timeouts seem to happen...

p

**Comment by krukow** [comment]
I'm not sure I understand your last comment. 

Is it, or isn't it working with stomp-websocket? 

From the debug log with stomple, it looks like a problem in the underlying websocket implementation, or perhaps a firewall is blocking? I don't think it is something I can help with.

**Comment by WIP42** [comment]
sorry, no its just 'hangs' saying "Opening Web Socket" so not working, no timeout or exceptions on client or Hornet console.

I agree, seems like only i have the issue here;-) and working in virtualbox on WinXP means its something I have specifically to my setup.

For the record, I dont have any firewalls etc running (that I know of), just a plain Ubuntu 10.04 desktop.

Hopefully someone has more insight into my specific problem, thanks @Carl for all the assistance!
